create table developers (
    id int8 generated by default as identity,
    name text not null unique,
    team_id int8,
    primary key (id)
);

create table teams (
    id int8 generated by default as identity,
    description text,
    name text not null unique,
    primary key (id)
);

create sequence hibernate_sequence start 1 increment 1;

alter table if exists developers add constraint developers_teams_foreign_key foreign key (team_id) references teams;